import json
import subprocess
from pathlib import Path

from ai_factory.cli import main


def _run(
    target: Path,
    state_dir: Path,
    task: str,
    backend: str = "fake",
    extra_args: list[str] | None = None,
) -> int:
    return main(
        [
            "run",
            str(target),
            task,
            "--backend",
            backend,
            "--state-dir",
            str(state_dir),
            *(extra_args or []),
        ]
    )


def _load_run_dir(state_dir: Path) -> Path:
    run_dirs = list((state_dir / "runs").iterdir())
    assert len(run_dirs) == 1
    return run_dirs[0]


def _load_run_metadata(state_dir: Path) -> dict:
    return json.loads((_load_run_dir(state_dir) / "metadata.json").read_text())


# --- report.md ---------------------------------------------------------------------


def test_report_leads_with_risk_assessment_and_factory_vs_agent_claims(
    git_repo: Path, tmp_path: Path
) -> None:
    state_dir = tmp_path / "state"

    exit_code = _run(git_repo, state_dir, "fix a typo in the README")

    assert exit_code == 0
    report_text = (_load_run_dir(state_dir) / "report.md").read_text()

    risk_pos = report_text.index("## Risk Assessment")
    claims_pos = report_text.index("## Factory-verified vs agent-claimed")
    verify_pos = report_text.index("## Verification Gate")
    assert risk_pos < claims_pos < verify_pos
    assert "Factory-verified (authoritative)" in report_text
    assert "Agent-claimed (advisory only)" in report_text


def test_report_states_continued_and_why_for_auto_continued_run(
    git_repo: Path, tmp_path: Path
) -> None:
    state_dir = tmp_path / "state"

    exit_code = _run(git_repo, state_dir, "fix a typo in the README")

    assert exit_code == 0
    report_text = (_load_run_dir(state_dir) / "report.md").read_text()
    assert "**continued**" in report_text
    assert "auto-continued" in report_text


def test_report_states_paused_and_why_for_high_risk_run(git_repo: Path, tmp_path: Path) -> None:
    state_dir = tmp_path / "state"

    exit_code = _run(git_repo, state_dir, "add an OAuth login flow")

    assert exit_code == 0
    report_text = (_load_run_dir(state_dir) / "report.md").read_text()
    assert "**paused**" in report_text
    assert "risk classified" in report_text


def test_report_summarizes_changed_files_and_verification(git_repo: Path, tmp_path: Path) -> None:
    state_dir = tmp_path / "state"

    exit_code = _run(git_repo, state_dir, "fix a typo in the README")

    assert exit_code == 0
    report_text = (_load_run_dir(state_dir) / "report.md").read_text()
    assert "## Changed files" in report_text
    assert "FAKE_AGENT_CHANGE.md" in report_text
    assert "## Verification Gate" in report_text


def test_report_ends_with_concrete_next_steps(git_repo: Path, tmp_path: Path) -> None:
    state_dir = tmp_path / "state"

    exit_code = _run(git_repo, state_dir, "fix a typo in the README")

    assert exit_code == 0
    report_text = (_load_run_dir(state_dir) / "report.md").read_text()
    assert "## Next steps" in report_text
    assert "Inspect the worktree" in report_text
    assert "Review the diff" in report_text
    assert "Switch to the branch" in report_text
    next_steps_pos = report_text.index("## Next steps")
    assert next_steps_pos > report_text.index("## Risk Assessment")


# --- pr-body.md ---------------------------------------------------------------------


def test_pr_body_is_written_and_forge_neutral_with_expected_sections(
    git_repo: Path, tmp_path: Path
) -> None:
    state_dir = tmp_path / "state"

    exit_code = _run(git_repo, state_dir, "fix a typo in the README")

    assert exit_code == 0
    pr_body_path = _load_run_dir(state_dir) / "pr-body.md"
    assert pr_body_path.is_file()
    pr_body_text = pr_body_path.read_text()

    for heading in (
        "## Summary",
        "## What Changed",
        "## Why",
        "## Verification",
        "## Test Coverage Notes",
        "## Risks & Follow-ups",
        "## Human Review Notes",
    ):
        assert heading in pr_body_text

    # Forge-neutral: no GitHub/GitLab-specific syntax.
    assert "#" not in pr_body_text.replace("##", "").replace("#!", "")
    assert "@" not in pr_body_text

    assert "Generated by ai-factory" in pr_body_text
    assert "verify before merging" in pr_body_text


def test_pr_body_reflects_changed_files_and_verification(git_repo: Path, tmp_path: Path) -> None:
    state_dir = tmp_path / "state"

    exit_code = _run(git_repo, state_dir, "fix a typo in the README")

    assert exit_code == 0
    pr_body_text = (_load_run_dir(state_dir) / "pr-body.md").read_text()
    assert "FAKE_AGENT_CHANGE.md" in pr_body_text


def test_pr_body_written_even_when_run_pauses_after_plan(git_repo: Path, tmp_path: Path) -> None:
    state_dir = tmp_path / "state"

    exit_code = _run(git_repo, state_dir, "add an OAuth login flow")

    assert exit_code == 0
    pr_body_path = _load_run_dir(state_dir) / "pr-body.md"
    assert pr_body_path.is_file()
    assert "no files changed" in pr_body_path.read_text()


# --- --review Diff Review Phase ------------------------------------------------------


def test_review_defaults_to_skipped_without_the_flag(git_repo: Path, tmp_path: Path) -> None:
    state_dir = tmp_path / "state"

    exit_code = _run(git_repo, state_dir, "fix a typo in the README")

    assert exit_code == 0
    metadata = _load_run_metadata(state_dir)
    assert metadata["phases"]["review"]["status"] == "skipped"
    assert metadata["decision_gate"]["flags"]["review"] is False

    report_text = (_load_run_dir(state_dir) / "report.md").read_text()
    assert "skipped" in report_text.lower()


def test_review_runs_and_findings_land_in_metadata_and_report(
    git_repo: Path, tmp_path: Path
) -> None:
    state_dir = tmp_path / "state"

    exit_code = _run(
        git_repo, state_dir, "fix a typo in the README", extra_args=["--review"]
    )

    assert exit_code == 0
    metadata = _load_run_metadata(state_dir)
    review_phase = metadata["phases"]["review"]
    assert review_phase["status"] == "succeeded"
    assert review_phase["findings"]
    assert metadata["decision_gate"]["flags"]["review"] is True

    run_dir = _load_run_dir(state_dir)
    assert (run_dir / "review-output.md").is_file()

    report_text = (run_dir / "report.md").read_text()
    assert "## Diff Review" in report_text
    assert review_phase["summary"] in report_text


def test_review_does_not_run_when_gate_pauses_the_run(git_repo: Path, tmp_path: Path) -> None:
    state_dir = tmp_path / "state"

    exit_code = _run(
        git_repo, state_dir, "add an OAuth login flow", extra_args=["--review"]
    )

    assert exit_code == 0
    metadata = _load_run_metadata(state_dir)
    assert metadata["phases"]["review"]["status"] == "not_executed"
    assert metadata["outcome"] == "planned"


def test_review_contract_violation_halts_with_evidence_and_never_touches_target(
    git_repo: Path, tmp_path: Path
) -> None:
    state_dir = tmp_path / "state"

    exit_code = _run(
        git_repo,
        state_dir,
        "fix a typo in the README",
        backend="fake-review-violator",
        extra_args=["--review"],
    )

    assert exit_code == 1
    run_dir = _load_run_dir(state_dir)
    metadata = _load_run_metadata(state_dir)

    assert metadata["phases"]["plan"]["status"] == "succeeded"
    assert metadata["phases"]["implement"]["status"] == "succeeded"
    assert metadata["outcome"] == "contract_violation"
    assert metadata["phases"]["review"]["status"] == "contract_violation"

    violation_patch = (run_dir / "contract-violation.patch").read_text()
    assert "FAKE_AGENT_REVIEW_VIOLATION.md" in violation_patch

    report_text = (run_dir / "report.md").read_text()
    assert "Contract Violation" in report_text

    status = subprocess.run(
        ["git", "status", "--porcelain"], cwd=git_repo, capture_output=True, text=True
    ).stdout
    assert status == ""


# --- Never merges/pushes/opens a PR/remote op ---------------------------------------


def test_no_push_merge_or_remote_operation_occurs(git_repo: Path, tmp_path: Path) -> None:
    state_dir = tmp_path / "state"

    _run(git_repo, state_dir, "fix a typo in the README", extra_args=["--review"])
    _run(git_repo, state_dir, "add an OAuth login flow", extra_args=["--review"])

    # The target repo has no remotes and is left exactly where it started;
    # nothing in the run path can have pushed, merged, or opened a PR.
    remotes = subprocess.run(
        ["git", "remote"], cwd=git_repo, capture_output=True, text=True
    ).stdout
    assert remotes == ""
    branch_before = subprocess.run(
        ["git", "rev-parse", "--abbrev-ref", "HEAD"], cwd=git_repo, capture_output=True, text=True
    ).stdout.strip()
    assert not branch_before.startswith("factory/")
