"""Renders the forge-neutral `pr-body.md` (ADR-0003/0005/0011/0014,
CONTEXT.md: Run Report).

Forge-neutral: no GitHub/GitLab-specific syntax and no assumption of any
particular forge's issue-linking or mention conventions. The Factory never
opens a pull request itself (ADR-0003) -- this is a draft a human reviews and
pastes into whatever forge they use, after verifying it themselves.
"""

from __future__ import annotations

FOOTER = "_Generated by ai-factory; verify before merging._"


def _format_changed_files(changed_files: list[str]) -> list[str]:
    if not changed_files:
        return ["(no files changed)"]
    return [f"- `{path}`" for path in changed_files]


def _format_verification(verify_phase: dict) -> list[str]:
    if verify_phase.get("status") == "not_executed":
        return [f"- Verification Gate did not run: {verify_phase.get('reason') or 'n/a'}"]
    if verify_phase.get("degraded"):
        return [
            "- Verification Gate ran in **degraded mode**: no verification "
            "commands were detected (ADR-0005)."
        ]
    commands = verify_phase.get("commands")
    if not commands:
        return [f"- (gate did not run: {verify_phase.get('reason') or 'n/a'})"]
    return [
        f"- [{'PASS' if command['passed'] else 'FAIL'}] {command['key']}: `{command['command']}`"
        for command in commands
    ]


def _format_test_coverage(verify_phase: dict) -> list[str]:
    if verify_phase.get("status") == "not_executed":
        return ["- Not applicable: the Verification Gate never ran for this Run."]
    if verify_phase.get("degraded"):
        return [
            "- No verification commands were detected for this repo; test "
            "coverage was not exercised by the Factory."
        ]
    test_commands = [c for c in (verify_phase.get("commands") or []) if c["key"] == "test"]
    if not test_commands:
        return [
            "- No `test` command was detected/run for this repo (see "
            "Verification above for what did run)."
        ]
    return [
        f"- `{command['command']}` -> {'passed' if command['passed'] else 'FAILED'}"
        for command in test_commands
    ]


def _format_risks(risk: dict, fix_attempts: list[dict], review_phase: dict) -> list[str]:
    lines = [f"- Risk Level: **{risk.get('level', 'unknown')}**"]
    lines += [f"  - {reason}" for reason in (risk.get("reasons") or [])]
    if fix_attempts:
        lines.append(
            f"- Required {len(fix_attempts)} Fix Loop attempt(s) to pass the Verification Gate."
        )
    review_status = review_phase.get("status")
    if review_status == "succeeded":
        lines.append(
            f"- Diff Review: {review_phase.get('summary') or 'see report.md for findings'}"
        )
    elif review_status == "contract_violation":
        lines.append("- Diff Review reported a Contract Violation -- see report.md.")
    elif review_status == "failed":
        lines.append(f"- Diff Review did not complete: {review_phase.get('reason') or 'n/a'}")
    return lines


def render_pr_body(metadata: dict) -> str:
    task = metadata["task"]
    outcome = metadata["outcome"]
    outcome_reason = metadata.get("outcome_reason") or "n/a"
    phases = metadata.get("phases") or {}
    implement_phase = phases.get("implement", {})
    verify_phase = phases.get("verify", {})
    review_phase = phases.get("review", {})
    risk = metadata.get("risk") or {}
    fix_attempts = (metadata.get("fix_loop") or {}).get("attempts") or []
    changed_files = metadata.get("changed_files") or []
    implement_summary = implement_phase.get("summary") or (
        "(no changes were implemented for this Run)"
    )

    lines = [
        "## Summary",
        "",
        task,
        "",
        f"Run outcome: **{outcome}** -- {outcome_reason}",
        "",
        "## What Changed",
        "",
        *_format_changed_files(changed_files),
        "",
        "## Why",
        "",
        task,
        "",
        "## Verification",
        "",
        *_format_verification(verify_phase),
        "",
        "## Test Coverage Notes",
        "",
        *_format_test_coverage(verify_phase),
        "",
        "## Risks & Follow-ups",
        "",
        *_format_risks(risk, fix_attempts, review_phase),
        "",
        "## Human Review Notes",
        "",
        "- This change was proposed by an AI agent inside the AI Code Factory; "
        "the Factory has **not** merged, pushed, or opened a pull/merge request "
        "for it -- a human must review the diff and the Verification Gate "
        "results above before landing it.",
        f"- Agent-claimed summary (advisory only, not authoritative): {implement_summary}",
        "",
        "---",
        "",
        FOOTER,
        "",
    ]
    return "\n".join(lines)
